service: tag-checker

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http: POST /
